# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 3.4
    - 2.7
env:
    - GROUP=
    - GROUP=js/base
    - GROUP=js/notebook
    - GROUP=js/services
    - GROUP=js/tree
    - GROUP=js/widgets
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - sudo add-apt-repository -y ppa:pcarrier/ppa
    # Needed to get recent version of pandoc in ubntu 12.04
    - sudo add-apt-repository -y ppa:marutter/c2d4u
    - sudo apt-get update
    - sudo apt-get install pandoc casperjs libzmq3-dev
    - git clone --quiet --depth 1 https://github.com/minrk/travis-wheels travis-wheels
    - 'if [[ $GROUP == js* ]]; then python -m IPython.external.mathjax; fi'
    - 'if [[ $GROUP != js* ]]; then COVERAGE="--coverage xml"; fi'
install:
    - pip install -f travis-wheels/wheelhouse file://$PWD#egg=ipython[all] coveralls
script:
    - cd /tmp && iptest $GROUP $COVERAGE && cd -

matrix:
    include:
        - python: 3.3
          env: GROUP=

after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - coveralls
